version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "area/dependencies"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "github.com/spf13/viper"
      - dependency-name: "gocloud.dev"

  - package-ecosystem: "docker"
    directory: "/"
    labels:
      - "area/dependencies"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "area/dependencies"
    schedule:
      interval: "daily"
