version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "area/dependencies"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    open-pull-requests-limit: 10
    groups:
      k8s.io:
        patterns:
          - "k8s.io/*"
      sigs.k8s.io:
        patterns:
          - "sigs.k8s.io/*"
      github.com/aws/aws-sdk-go-v2:
        patterns:
          - "github.com/aws/aws-sdk-go-v2*"
      cloud.google.com/go:
        patterns:
          - "cloud.google.com/go*"
      github.com/Azure:
        patterns:
          - "github.com/Azure/*"
      github.com/hashicorp:
        patterns:
          - "github.com/hashicorp/*"

  - package-ecosystem: "docker"
    directory: "/"
    labels:
      - "area/dependencies"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "area/dependencies"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    open-pull-requests-limit: 10
    groups:
      actions:
        patterns:
          - "*"
