{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "vault-secrets-webhook.fullname" . }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "vault-secrets-webhook.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: mutating-webhook
    {{- if .Values.metrics.serviceMonitor.additionalLabels }}
{{ toYaml .Values.metrics.serviceMonitor.additionalLabels | indent 4 }}
    {{- end }}
spec:
  endpoints:
  - interval: {{ .Values.metrics.serviceMonitor.scrapeInterval }}
    port: metrics
    scheme: {{ .Values.metrics.serviceMonitor.scheme }}
    {{- if .Values.metrics.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ toYaml .Values.metrics.serviceMonitor.metricRelabelings | indent 6 }}
    {{- end }}
    {{- if .Values.metrics.serviceMonitor.relabelings }}
    relabelings:
{{ toYaml .Values.metrics.serviceMonitor.relabelings | indent 6 }}
    {{- end }}
    {{- if and .Values.metrics.serviceMonitor.tlsConfig }}
    tlsConfig:
{{ toYaml .Values.metrics.serviceMonitor.tlsConfig | indent 6 }}
    {{- end }}
  jobLabel: {{ template "vault-secrets-webhook.name" . }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "vault-secrets-webhook.name" . }}
      app.kubernetes.io/instance: "{{ .Release.Name }}"
{{- end }}
