run:
    skip-dirs:
        - operator

linters-settings:
    golint:
        min-confidence: 0.1
    goimports:
        local-prefixes: github.com/banzaicloud/bank-vaults

linters:
    enable-all: true
    disable:
        - maligned
        - funlen
        - dupl
        - wsl
        - lll

        # TODO: fixme
        - goimports
        - gochecknoglobals
        - gochecknoinits
        - unparam
        - goconst
        - gocognit
        - errcheck
        - unconvert
        - whitespace
        - misspell
        - nakedret
        - gofmt
        - golint
        - scopelint
        - gocritic
        - staticcheck
        - gosimple
        - stylecheck
        - gocyclo
