builds:
    -
        id: bank-vaults
        main: ./cmd/bank-vaults
        binary: bank-vaults
        env:
            - CGO_ENABLED=0
        ldflags: "-s -w -X main.version={{ .Version }} -X main.commitHash={{ .ShortCommit }} -X main.buildDate={{ .Date }}"
        goos:
            - linux
            - darwin
            - windows
        goarch:
            - amd64
            - arm64

    -
        id: vault-env
        main: ./cmd/vault-env
        binary: vault-env
        env:
            - CGO_ENABLED=0
        ldflags: "-s -w -X main.version={{ .Version }} -X main.commitHash={{ .ShortCommit }} -X main.buildDate={{ .Date }}"
        goos:
            - linux
            - darwin
            - windows
        goarch:
            - amd64
            - arm64
archives:
    -
        id: bank-vaults-targz
        name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"
        builds:
            - bank-vaults
        format_overrides:
            - goos: windows
              format: zip
    -
        id: vault-env
        name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"
        builds:
            - vault-env
        format_overrides:
            - goos: windows
              format: zip

checksum:
    name_template: "bank-vaults_checksums.txt"

changelog:
    skip: false

brews:
    -
        tap:
            owner: banzaicloud
            name: homebrew-tap
        folder: Formula
        homepage: https://banzaicloud.com/products/bank-vaults/
        description: A Vault swiss-army knife CLI with Kubernetes support
        test: |
            system "#{bin}/bank-vaults"
            system "#{bin}/vault-env"
