ARG GO_VERSION=1.13

FROM golang:${GO_VERSION}-alpine AS builder

RUN apk add --update --no-cache ca-certificates make git curl mercurial

ARG GOPROXY

RUN mkdir -p /build
WORKDIR /build

COPY go.* /build/
COPY pkg/sdk/go.* /build/pkg/sdk/
RUN go mod download

COPY . /build
RUN go mod download

COPY . /go/src/${PACKAGE}
RUN CGO_ENABLED=0 go install ./cmd/vault-env


FROM vault:1.2.3

COPY --from=builder /go/bin/vault-env /usr/local/bin/vault-env
