# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

required = [
  "k8s.io/code-generator/cmd/client-gen"
]

[[constraint]]
  name = "cloud.google.com/go"
  version = "0.20.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.29"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"

[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "0.10.2"

[[constraint]]
  name = "github.com/Masterminds/sprig"
  version = "v2.15.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/spf13/cast"
  version = "1.2.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.11"
  
[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.11"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-8.0"

[[constraint]]
  name = "k8s.io/code-generator"
  branch = "release-1.11"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.3"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.3"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  # The version rule is used for a specific release and the master branch for in between releases.
  branch = "master"
  # version = "=v0.0.5"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    non-go = false
    go-tests = false

  [[prune.project]]
    name = "k8s.io/gengo"
    unused-packages = false
    non-go = false
    go-tests = false

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "15.2.0"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "10.6.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/gin-gonic/gin"

[[constraint]]
  name = "github.com/qor/qor"
  branch = "master"

# Alibaba and AWS SDK are no friends, they can't agree in go-jmespath
[[override]]
  name = "github.com/jmespath/go-jmespath"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/aliyun/alibaba-cloud-sdk-go"

[[constraint]]
  name = "github.com/coreos/etcd-operator"
  version = "0.9.2"
