// Copyright © 2019 Banzai Cloud
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/banzaicloud/bank-vaults/operator/pkg/apis/vault/v1alpha1"
	scheme "github.com/banzaicloud/bank-vaults/operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VaultSpecsGetter has a method to return a VaultSpecInterface.
// A group's client should implement this interface.
type VaultSpecsGetter interface {
	VaultSpecs(namespace string) VaultSpecInterface
}

// VaultSpecInterface has methods to work with VaultSpec resources.
type VaultSpecInterface interface {
	Create(*v1alpha1.VaultSpec) (*v1alpha1.VaultSpec, error)
	Update(*v1alpha1.VaultSpec) (*v1alpha1.VaultSpec, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.VaultSpec, error)
	List(opts v1.ListOptions) (*v1alpha1.VaultSpecList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.VaultSpec, err error)
	VaultSpecExpansion
}

// vaultSpecs implements VaultSpecInterface
type vaultSpecs struct {
	client rest.Interface
	ns     string
}

// newVaultSpecs returns a VaultSpecs
func newVaultSpecs(c *VaultV1alpha1Client, namespace string) *vaultSpecs {
	return &vaultSpecs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the vaultSpec, and returns the corresponding vaultSpec object, and an error if there is any.
func (c *vaultSpecs) Get(name string, options v1.GetOptions) (result *v1alpha1.VaultSpec, err error) {
	result = &v1alpha1.VaultSpec{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vaultspecs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VaultSpecs that match those selectors.
func (c *vaultSpecs) List(opts v1.ListOptions) (result *v1alpha1.VaultSpecList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.VaultSpecList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vaultspecs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vaultSpecs.
func (c *vaultSpecs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("vaultspecs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a vaultSpec and creates it.  Returns the server's representation of the vaultSpec, and an error, if there is any.
func (c *vaultSpecs) Create(vaultSpec *v1alpha1.VaultSpec) (result *v1alpha1.VaultSpec, err error) {
	result = &v1alpha1.VaultSpec{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("vaultspecs").
		Body(vaultSpec).
		Do().
		Into(result)
	return
}

// Update takes the representation of a vaultSpec and updates it. Returns the server's representation of the vaultSpec, and an error, if there is any.
func (c *vaultSpecs) Update(vaultSpec *v1alpha1.VaultSpec) (result *v1alpha1.VaultSpec, err error) {
	result = &v1alpha1.VaultSpec{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vaultspecs").
		Name(vaultSpec.Name).
		Body(vaultSpec).
		Do().
		Into(result)
	return
}

// Delete takes name of the vaultSpec and deletes it. Returns an error if one occurs.
func (c *vaultSpecs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vaultspecs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vaultSpecs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vaultspecs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched vaultSpec.
func (c *vaultSpecs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.VaultSpec, err error) {
	result = &v1alpha1.VaultSpec{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("vaultspecs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
