name: 🐛 Bug report
description: Report a bug to help us improve Bank-Vaults
labels: [kind/bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a bug report!

        Please fill out the template below to make it easier to debug your problem.

        If you are not sure if it is a bug or not, you can contact us via the available [support channels](https://bank-vaults.dev/docs/support).
  - type: checkboxes
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed all of the following.
      options:
        - label: I have searched the [issue tracker](https://www.github.com/bank-vaults/bank-vaults/issues) for an issue that matches the one I want to file, without success.
          required: true
        - label: I am not looking for support or already pursued the available [support channels](https://bank-vaults.dev/docs/support) without success.
          required: true
        - label: I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct).
          required: true
  - type: input
    attributes:
      label: Version
      description: What version of the Bank-Vaults CLI are you using?
      placeholder: 1.20.0
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: A clear description of what actually happens.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior if it is not self-explanatory.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
  - type: textarea
    attributes:
      label: Logs
      description: Bank-Vaults CLI logs (if relevant).
      render: shell
  - type: textarea
    attributes:
      label: Additional Information
      description: Links? References? Anything that will give us more context about the issue that you are encountering!
