apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: kurun://cmd/examples/main.go
    name: nginx
    volumeMounts:
    - mountPath: /var/run/secrets/tokens
      name: vault-token
  serviceAccountName: default
  volumes:
  - name: vault-token
    projected:
      sources:
      - serviceAccountToken:
          path: vault-token
          expirationSeconds: 7200
          audience: vault
