apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
            labels:
              app.kubernetes.io/name: hello-secrets
            annotations:
              vault.security.banzaicloud.io/vault-addr: "https://vault:8200"
              vault.security.banzaicloud.io/vault-tls-secret: vault-tls
        spec:
          containers:
          - name: alpine
            image: alpine
            command: ["sh", "-c", "echo $AWS_SECRET_ACCESS_KEY"]
            env:
            - name: AWS_SECRET_ACCESS_KEY
              value: vault:secret/data/accounts/aws#${.AWS_SECRET_ACCESS_KEY} # Go templates are also supported with ${} delimiters
          restartPolicy: OnFailure