apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-test
  annotations:
    vault.banzaicloud.io/vault-addr: "https://vault:8200"
    vault.banzaicloud.io/vault-role: "default"
    vault.banzaicloud.io/vault-skip-verify: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: alpine
        image: alpine
        command: ["sh", "-c", "env && echo going to sleep... && sleep 10000"]
        env:
        - name: AWS_SECRET_ACCESS_KEY
          value: vault:secret/data/valami/aws#AWS_SECRET_ACCESS_KEY
