// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/banzaicloud/bank-vaults/operator/pkg/apis/vault/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVaultLists implements VaultListInterface
type FakeVaultLists struct {
	Fake *FakeVaultV1alpha1
	ns   string
}

var vaultlistsResource = schema.GroupVersionResource{Group: "vault.banzaicloud.com", Version: "v1alpha1", Resource: "vaultlists"}

var vaultlistsKind = schema.GroupVersionKind{Group: "vault.banzaicloud.com", Version: "v1alpha1", Kind: "VaultList"}

// Get takes name of the vaultList, and returns the corresponding vaultList object, and an error if there is any.
func (c *FakeVaultLists) Get(name string, options v1.GetOptions) (result *v1alpha1.VaultList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(vaultlistsResource, c.ns, name), &v1alpha1.VaultList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultList), err
}

// List takes label and field selectors, and returns the list of VaultLists that match those selectors.
func (c *FakeVaultLists) List(opts v1.ListOptions) (result *v1alpha1.VaultList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(vaultlistsResource, vaultlistsKind, c.ns, opts), &v1alpha1.VaultList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultList), err
}

// Watch returns a watch.Interface that watches the requested vaultLists.
func (c *FakeVaultLists) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(vaultlistsResource, c.ns, opts))

}

// Create takes the representation of a vaultList and creates it.  Returns the server's representation of the vaultList, and an error, if there is any.
func (c *FakeVaultLists) Create(vaultList *v1alpha1.VaultList) (result *v1alpha1.VaultList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(vaultlistsResource, c.ns, vaultList), &v1alpha1.VaultList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultList), err
}

// Update takes the representation of a vaultList and updates it. Returns the server's representation of the vaultList, and an error, if there is any.
func (c *FakeVaultLists) Update(vaultList *v1alpha1.VaultList) (result *v1alpha1.VaultList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(vaultlistsResource, c.ns, vaultList), &v1alpha1.VaultList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultList), err
}

// Delete takes name of the vaultList and deletes it. Returns an error if one occurs.
func (c *FakeVaultLists) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(vaultlistsResource, c.ns, name), &v1alpha1.VaultList{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVaultLists) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(vaultlistsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.VaultList{})
	return err
}

// Patch applies the patch and returns the patched vaultList.
func (c *FakeVaultLists) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.VaultList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(vaultlistsResource, c.ns, name, data, subresources...), &v1alpha1.VaultList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultList), err
}
