// Copyright © 2019 Banzai Cloud
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/banzaicloud/bank-vaults/operator/pkg/apis/vault/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVaults implements VaultInterface
type FakeVaults struct {
	Fake *FakeVaultV1alpha1
	ns   string
}

var vaultsResource = schema.GroupVersionResource{Group: "vault.banzaicloud.com", Version: "v1alpha1", Resource: "vaults"}

var vaultsKind = schema.GroupVersionKind{Group: "vault.banzaicloud.com", Version: "v1alpha1", Kind: "Vault"}

// Get takes name of the vault, and returns the corresponding vault object, and an error if there is any.
func (c *FakeVaults) Get(name string, options v1.GetOptions) (result *v1alpha1.Vault, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(vaultsResource, c.ns, name), &v1alpha1.Vault{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Vault), err
}

// List takes label and field selectors, and returns the list of Vaults that match those selectors.
func (c *FakeVaults) List(opts v1.ListOptions) (result *v1alpha1.VaultList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(vaultsResource, vaultsKind, c.ns, opts), &v1alpha1.VaultList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VaultList{ListMeta: obj.(*v1alpha1.VaultList).ListMeta}
	for _, item := range obj.(*v1alpha1.VaultList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vaults.
func (c *FakeVaults) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(vaultsResource, c.ns, opts))

}

// Create takes the representation of a vault and creates it.  Returns the server's representation of the vault, and an error, if there is any.
func (c *FakeVaults) Create(vault *v1alpha1.Vault) (result *v1alpha1.Vault, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(vaultsResource, c.ns, vault), &v1alpha1.Vault{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Vault), err
}

// Update takes the representation of a vault and updates it. Returns the server's representation of the vault, and an error, if there is any.
func (c *FakeVaults) Update(vault *v1alpha1.Vault) (result *v1alpha1.Vault, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(vaultsResource, c.ns, vault), &v1alpha1.Vault{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Vault), err
}

// Delete takes name of the vault and deletes it. Returns an error if one occurs.
func (c *FakeVaults) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(vaultsResource, c.ns, name), &v1alpha1.Vault{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVaults) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(vaultsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.VaultList{})
	return err
}

// Patch applies the patch and returns the patched vault.
func (c *FakeVaults) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Vault, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(vaultsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Vault{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Vault), err
}
