// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/banzaicloud/bank-vaults/operator/pkg/client/clientset/versioned/typed/vault/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeVaultV1alpha1 struct {
	*testing.Fake
}

func (c *FakeVaultV1alpha1) VaultLists(namespace string) v1alpha1.VaultListInterface {
	return &FakeVaultLists{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeVaultV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
