# Installing Prometheus Operator is required to make this example work:
# kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/master/bundle.yaml
#
# After applying this check the Vault targets on the Prometheus UI:
#  1. kubectl port-forward service/prometheus-operated 9090
#  2. open http://localhost:9090/targets

apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
spec:
  size: 2
  image: vault:1.6.2

  # Specify the ServiceAccount where the Vault Pod and the Bank-Vaults configurer/unsealer is running
  serviceAccount: vault

  # Specify the Service's type where the Vault Service is exposed
  serviceType: ClusterIP

  statsdDisabled: true

  volumeMounts:
    - name: vault-file
      mountPath: /vault/file

  # Use local disk to store Vault raft data, see config section.
  volumeClaimTemplates:
    - metadata:
        name: vault-file
      spec:
        # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
        # storageClassName: ""
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi

  # Describe where you would like to store the Vault unseal keys and root token.
  unsealConfig:
    kubernetes:
      secretNamespace: default

  # A YAML representation of a final vault config file.
  # See https://www.vaultproject.io/docs/configuration/ for more information.
  config:
    storage:
      raft:
        path: "/vault/file"
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
        # If you are using HA I suggest uncommenting this part, please check:
        # https://www.vaultproject.io/docs/configuration/telemetry#prometheus
        # In case this is uncommented, the whole token ceremony below with
        # Vault Agent is unnecessary.
        telemetry:
          unauthenticated_metrics_access: true
    telemetry:
      prometheus_retention_time: "24h"
      disable_hostname: true
    api_addr: https://vault.default:8200
    cluster_addr: "https://${.Env.POD_NAME}:8201"
    ui: true

  serviceMonitorEnabled: true

  serviceRegistrationEnabled: true

  # See: https://banzaicloud.com/docs/bank-vaults/cli-tool/#example-external-vault-configuration
  # The repository also contains a lot examples in the deploy/ and operator/deploy directories.
  externalConfig:
    policies:
      - name: prometheus-operator
        rules: path "sys/metrics" {
          capabilities = ["list", "read"]
          }

    auth:
      - type: kubernetes
        roles:
          - name: prometheus
            bound_service_account_names: prometheus
            bound_service_account_namespaces: default
            policies: prometheus-operator
            ttl: 4h

---

# Create a Prometheus instance, that has the token to the above Vault instance
# in case unauthenticated_metrics_access is disabled (false by default):
# https://www.vaultproject.io/docs/configuration/listener/tcp#telemetry-parameters

apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-config
data:
  vault-agent-config.hcl: |
    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role = "prometheus"
        }
      }

      sink "file" {
        config = {
          path = "/home/vault/config-out/.vault-token"
        }
      }
    }

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus

---

apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      app.kubernetes.io/name: vault
  configMaps:
  - vault-agent-config
  containers:
  - name: vault-agent-auth
    image: vault
    securityContext:
      runAsUser: 65534
    volumeMounts:
      - name: configmap-vault-agent-config
        mountPath: /etc/vault
      - name: config-out
        mountPath: /home/vault/config-out
    env:
      - name: VAULT_ADDR
        value: https://vault:8200
      - name: VAULT_SKIP_VERIFY
        value: "true"
    command: ["vault"]
    args:
      [
        "agent",
        "-config=/etc/vault/vault-agent-config.hcl",
        "-log-level=debug",
      ]
