kind: ServiceAccount
apiVersion: v1
metadata:
  name: etcd-operator

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: etcd-operator
rules:
  - apiGroups:
      - etcd.database.coreos.com
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: etcd-operator
subjects:
  - kind: ServiceAccount
    name: etcd-operator
roleRef:
  kind: Role
  name: etcd-operator
  apiGroup: rbac.authorization.k8s.io
