apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vaults.vault.banzaicloud.com
spec:
  group: vault.banzaicloud.com
  names:
    kind: Vault
    listKind: VaultList
    plural: vaults
    singular: vault
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vault-operator
  template:
    metadata:
      labels:
        name: vault-operator
    spec:
      containers:
        - name: vault-operator
          image: banzaicloud/vault-operator:latest
          imagePullPolicy: IfNotPresent
          command:
          - vault-operator
          env:
            # OPERATOR_NAMESPACE defines the namespace where the operator watches
            # for CRD objects, if not defined all namespaces are whatched.
          - name: OPERATOR_NAMESPACE
            value: default
            # LOG_LEVEL defines the logging level in Logrus log levels
          - name: OPERATOR_LOG_LEVEL
            value: info
      serviceAccount: vault-operator
