apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vaults.vault.banzaicloud.com
spec:
  group: vault.banzaicloud.com
  names:
    kind: Vault
    listKind: VaultList
    plural: vaults
    singular: vault
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vault-operator
  template:
    metadata:
      labels:
        name: vault-operator
    spec:
      serviceAccountName: vault-operator
      containers:
        - name: vault-operator
          image: banzaicloud/vault-operator:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 60000
              name: metrics
          command:
            - vault-operator
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            # OPERATOR_NAMESPACE is here only for backward compatibility, the new SDK uses WATCH_NAMESPACE instead
            #            - name: OPERATOR_NAMESPACE
            #              value: ""
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "vault-operator"
