apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-operator

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - configmaps
      - secrets
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - list
      - get
      - create
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - list
      - get
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - update
      - list
      - get
      - create
  - apiGroups:
      - vault.banzaicloud.com
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - etcd.database.coreos.com
    resources:
      - "*"
    verbs:
      - "*"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-operator
rules:
- apiGroups:
    - ""
  resources:
    - namespaces
  verbs:
    - get
    - list
    - watch
- apiGroups: [""]
  resources: ["secrets"]
  verbs:
    - create
    - update
    - get
    - list
    - watch

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-operator
subjects:
  - kind: ServiceAccount
    name: vault-operator
    namespace: default
roleRef:
  kind: Role
  name: vault-operator
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-operator
subjects:
  - kind: ServiceAccount
    name: vault-operator
    namespace: default
roleRef:
  kind: ClusterRole
  name: vault-operator
  apiGroup: rbac.authorization.k8s.io
