// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// VaultListerExpansion allows custom methods to be added to
// VaultLister.
type VaultListerExpansion interface{}

// VaultNamespaceListerExpansion allows custom methods to be added to
// VaultNamespaceLister.
type VaultNamespaceListerExpansion interface{}
