apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "vault.fullname" . }}-statsd-mapping"
  labels:
    helm.sh/chart: {{ template "vault.chart" . }}
    app.kubernetes.io/name: "{{ template "vault.name" . }}"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
data:
  statsd-mapping.conf: |
{{ toYaml .Values.statsd.config | indent 6 }}
