apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "vault.fullname" . }}-statsd-mapping"
  labels:
    app: "{{ template "vault.name" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  statsd-mapping.conf: |
{{ toYaml .Values.statsd.config | indent 6 }}
