{{- if and .Values.unsealer.metrics.enabled .Values.unsealer.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "vault.fullname" . }}-unsealer
  labels:
    helm.sh/chart: {{ template "vault.chart" . }}
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.unsealer.metrics.serviceMonitor.additionalLabels }}
{{ toYaml .Values.unsealer.metrics.serviceMonitor.additionalLabels | indent 4 }}
    {{- end }}
spec:
  endpoints:
  - interval: 30s
    port: metrics
    {{- if .Values.unsealer.metrics.serviceMonitor.relabellings }}
    metricRelabelings:
{{ toYaml .Values.unsealer.metrics.serviceMonitor.relabellings | indent 4 }}
    {{- end }}
  jobLabel: {{ include "vault.name" . }}
  namespaceSelector:
    matchNames:
    - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "vault.name" . }}
      app.kubernetes.io/instance: "{{ .Release.Name }}"

---

apiVersion: v1
kind: Service
metadata:
  annotations:
  name: {{ include "vault.fullname" . }}-statsd
  labels:
    helm.sh/chart: {{ template "vault.chart" . }}
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: {{ .Values.statsd.metrics.port }}
    protocol: TCP
    targetPort: {{ .Values.statsd.metrics.port }}
  selector:
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: {{ include "vault.fullname" . }}-unsealer
  labels:
    helm.sh/chart: {{ template "vault.chart" . }}
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: {{ .Values.unsealer.metrics.port }}
    protocol: TCP
    targetPort: {{ .Values.unsealer.metrics.port }}
  selector:
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
  sessionAffinity: None
  type: ClusterIP

{{- end }}
