{{- $cn := include "vault.fullname" . -}}
{{- $externalDNS := print $cn "." .Release.Namespace -}}
{{- $ca := genCA "vault-ca" 365 -}}
{{- $cert := genSignedCert $cn (list "127.0.0.1") (list $cn $externalDNS) 365 $ca -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vault.fullname" . }}-tls
  labels:
    app: {{ template "vault.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  ca.crt: {{ $ca.Cert | b64enc }}
  ca.key: {{ $ca.Key | b64enc }}
  server.crt: {{ $cert.Cert | b64enc }}
  server.key: {{ $cert.Key | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "vault.fullname" . }}-config"
  labels:
    app: "{{ template "vault.name" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  config.json:
    {{ if .Values.vault.config.storage }}
    {{ .Values.vault.config | toPrettyJson | b64enc }}
    {{ else }}
    {{ (merge .Values.vault.config .Values.vault.defaultStorage) | toPrettyJson | b64enc }}
    {{ end }}
  vault-config.yml:
    {{ .Values.vault.externalConfig | toPrettyJson | b64enc }}
