apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "vault.fullname" . }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "vault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.serviceAccount.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  