name: Goreleaser
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-dev.[0-9]+"
env:
    GO_VERSION: 1.19.2
jobs:
  docker:
    name: Goreleaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
            go-version: ${{ env.GO_VERSION }}

      - name: Install xgo
        run: go install github.com/crazy-max/xgo@latest

      - name: Install goreleaser
        run: go install github.com/goreleaser/goreleaser@latest

      - name: Run goreleaser
        run: goreleaser release --clean --timeout 2h
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Run GoReleaser
      #   uses: goreleaser/goreleaser-action@v4
      #   with:
      #       version: latest
      #       args: release --clean --timeout 2h
      #   env:
      #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
